dbt_postgres:
  outputs:
    dev:
      dbname: neuma
      host: postgres
      pass: post33##
      port: 5432
      schema: DWH
      threads: 1
      type: postgres
      user: postgres
  target: dev
postgres_dbt:
  outputs:
    dev:
      dbname: neuma
      host: localhost
      pass: post33##
      port: 5432
      schema: DWH
      threads: 1
      type: postgres
      user: postgres
  target: dev
